name: Build and Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [10.x, 12.x, 13.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get Tag Version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get Tag Message
        # run: echo "TAG_MESSAGE=$(git tag -l --format='%(contents)')" >> $GITHUB_ENV
        run: echo "TAG_MESSAGE=$(git log --format=%B -n 1)" >> $GITHUB_ENV



      - name: Test
        run: |
          echo $TAG_VERSION
          echo ${{ env.TAG_VERSION }}
          echo $TAG_MESSAGE
          echo ${{ env.TAG_MESSAGE }}

      - name: Install dependencies
        run: npm ci

      - name: Lint the project
        run: npm run lint

      - name: Build the project
        run: npm run build
        env:
          CI: true
