---
name: "Release"

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: read


jobs:
  release:

    # disable this job for now. will use manual releases.
    if: false

    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Create Release
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          # Create release
          gh release create "${{  github.ref_name }}" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${{  github.ref_name }}" \
              --generate-notes
